# Generated by Django 3.1.2 on 2023-06-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carroitem',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
