# Generated by Django 3.1.2 on 2023-06-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230619_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carroitem',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
