# Generated by Django 3.1.2 on 2023-06-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_compra_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('Validación', 'Validación'), ('Preparación', 'Preparación'), ('Reparto', 'Reparto'), ('Entregado', 'Entregado')], default='validacion', max_length=20),
        ),
    ]
