# Generated by Django 3.1.2 on 2023-06-22 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230621_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compraitem',
            name='carro_item',
        ),
        migrations.AddField(
            model_name='compraitem',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='compraitem',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
        migrations.AddField(
            model_name='compraitem',
            name='subtotal',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
